// export const serviceConstants = {
//   GET_ALL_SERVICE: 'GET_ALL_SERVICE',
// };

export const serviceConstants = {
  GET_ALL_SERVICE_REQUEST: 'GET_ALL_SERVICE_REQUEST',
  GET_ALL_SERVICE_SUCCESS: 'GET_ALL_SERVICE_SUCCESS',
  GET_ALL_SERVICE_FAILURE: 'GET_ALL_SERVICE_FAILURE',
  ADD_NEW_SERVICE_REQUEST: 'ADD_NEW_SERVICE_REQUEST',
  ADD_NEW_SERVICE_SUCCESS: 'ADD_NEW_SERVICE_SUCCESS',
  ADD_NEW_SERVICE_FAILURE: 'ADD_NEW_SERVICE_FAILURE',
};

export const orderConstants = {
  GET_ALL_ORDER_REQUEST: 'GET_ALL_ORDER_REQUEST',
  GET_ALL_ORDER_SUCCESS: 'GET_ALL_ORDER_SUCCESS',
  GET_ALL_ORDER_FAILURE: 'GET_ALL_ORDER_FAILURE',
  ADD_NEW_ORDER_REQUEST: 'ADD_NEW_ORDER_REQUEST',
  ADD_NEW_ORDER_SUCCESS: 'ADD_NEW_ORDER_SUCCESS',
  ADD_NEW_ORDER_FAILURE: 'ADD_NEW_ORDER_FAILURE',
};
